# fly.toml app configuration file generated for aftermath-core-canary on 2024-02-02T10:45:58-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aftermath-core-canary'
primary_region = 'lhr'

[env]
BLITZ_STARS_API_URL = "https://www.blitzstars.com/api"
CACHE_WG_PROXY_URL = 'http://aftermath-wg-proxy-cache.internal:9090/v1'
FRONTEND_URL = 'https://canary.amth.one'
LIVE_WG_PROXY_URL = 'http://aftermath-wg-proxy-live.internal:9090/v1'
LOG_LEVEL = 'info'
NETWORK = 'tcp'
PORT = '9090'
SCHEDULER_ENABLED = 'false'
WOT_INSPECTOR_TANK_DB_URL = 'https://armor.wotinspector.com/static/armorinspector/tank_db_blitz.js'
WOT_INSPECTOR_REPLAYS_URL = 'https://api.wotinspector.com/v2/blitz/replays/'

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 256
