# fly.toml app configuration file generated for aftermath-core on 2024-02-01T16:49:05-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aftermath-core'
primary_region = 'lhr'

[env]
WOT_INSPECTOR_TANK_DB_URL = 'https://armor.wotinspector.com/static/armorinspector/tank_db_blitz.js'
WOT_INSPECTOR_REPLAYS_URL = 'https://api.wotinspector.com/v2/blitz/replays/'
CACHE_WG_PROXY_URL = 'http://aftermath-wg-proxy-cache.internal:9090/v1'
LIVE_WG_PROXY_URL = 'http://aftermath-wg-proxy-live.internal:9090/v1'
BLITZ_STARS_API_URL = "https://www.blitzstars.com/api"
FRONTEND_URL = 'https://amth.one'
INDEX_SYNC_ENABLED = 'true'
SCHEDULER_ENABLED = 'true'
LOG_LEVEL = 'info'
NETWORK = 'tcp'
PORT = '9090'

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 256
