version: 3

dotenv: ['.env']

# Used for --watch
interval: '500ms'

tasks:
  dev:
    desc: Run the application in development mode with hot reload
    cmds:
      - air

  dev-stats:
    desc: Run the complete rendering pipeline test file, this is useful when making UI changes
    watch: true
    sources:
      - '**/*.go'
    cmds:
      - go test -timeout 30s --count=1 -run TestFullSessionRenderPipeline github.com/cufee/aftermath-core -v
  dev-preview:
    desc: Run the complete rendering pipeline test file, this is useful when making UI changes
    watch: true
    sources:
      - '**/*.go'
    cmds:
      - go test -timeout 30s --count=1 -run TestFullPreviewRenderPipeline github.com/cufee/aftermath-core -v
  dev-replay:
    desc: Run the complete rendering pipeline test file, this is useful when making UI changes
    watch: true
    sources:
      - '**/*.go'
    cmds:
      - go test -timeout 30s --count=1 -run TestFullReplayRenderPipeline github.com/cufee/aftermath-core -v
  dev-period:
    desc: Run the complete rendering pipeline test file, this is useful when making UI changes
    watch: true
    sources:
      - '**/*.go'
    cmds:
      - go test -timeout 30s --count=1 -run TestFullPeriodRenderPipeline github.com/cufee/aftermath-core -v

  test:
    desc: Run tests
    cmds:
      - go test ./... -v          
  upgrade:
    desc: Upgrade dependencies
    cmds:
      - go get -u ./...

  build:docker:
    desc: Build the application for Docker
    cmds:
      - go build -o {{ .CLI_ARGS | default "app" }} .
  build:image:
    desc: Build the Docker image
    cmds:
      - docker build --progress=plain --platform linux/amd64 -t {{ .CLI_ARGS | default "github.com/cufee/aftermath-core" }} .

  accent-export:
    cmds:
      - accent export