name: Fly Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy app to production
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: npm install -g accent-cli && accent export
        env:
          ACCENT_API_KEY: ${{ secrets.ACCENT_API_KEY }}
      - run: flyctl deploy --remote-only -c master.fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
